# Buenas prácticas
# https://www.coddykit.com/pages/blog-detail?id=512499&slug=dodging-disasters-common-groovy-gradle-mistakes-and-how-to-avoid-them

# Configuración del entorno Gradle
org.gradle.console=verbose
org.gradle.daemon=true
org.gradle.caching=true

# https://github.com/graalvm/native-build-tools/issues/427#issuecomment-1661254410
org.gradle.configuration-cache=true
org.gradle.configuration-cache.stable = true
org.gradle.configuration-cache.problems = warn

org.gradle.jvmargs=-XX:+IgnoreUnrecognizedVMOptions --sun-misc-unsafe-memory-access=allow
