logging:
  level:
    org.springframework.security: debug
    es.ubu.lsi.ubumonitorweb: debug

security:
  public-routes:
    - /
    - /index.html
    - /favicon.png
    - /logo1.png
    - /_app/**
    - /actuator**
    - /swagger-ui/**
    - /swagger-ui/index.html
    - /v3/api-docs
    - /api/auth/login
