security:
  public-routes:
    - /
    - /index.html
    - /favicon.png
    - /logo1.png
    - /_app/**
    - /auth/login

management:
  endpoints:
    access:
      default: none

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
