spring:
  application:
    name: ubumonitorweb
  web:
    locale: en
  messages:
    fallback-to-system-locale: false
  profiles:
    default: dev

server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: strict

service:
  default:
    host-header: Moodle-Host
    send-headers:
      - Accept-Language
    headers:
      Content-Type: application/x-www-form-urlencoded

  profiles:
    credentials:
      endpoint: /login/token.php
      params:
        service: moodle_mobile_app

    principal:
      endpoint: /webservice/rest/server.php
      params:
        moodlewsrestformat: json
        wsfunction: core_webservice_get_site_info

    webservice:
      endpoint: /webservice/rest/server.php
      params:
        moodlewsrestformat: json
      suppliers:
        wsfunction:
          location: param
          bean: es.ubu.lsi.ubumonitorweb.core.exception.ServiceFunctionParamSupplier
