spring:
  application:
    name: ubumonitorweb
  profiles:
    active: dev
  web:
    locale: en
    error.include-stacktrace: never
  messages:
    fallback-to-system-locale: false

server:
  servlet:
    session:
      cookie:
        same-site: strict

logging:
  level:
    org.springframework.security: trace
    es.ubu.lsi.ubumonitorweb: debug

security:
  public-routes:
    - /auth/login
    - /actuator**
    - /swagger-ui**
    - /v3/api-docs**
  logout-url: /auth/logout

service:
  default:
    host-header: Moodle-Host
    send-headers:
      - Accept-Language
    headers:
      Content-Type: application/x-www-form-urlencoded

  profiles:
    token:
      endpoint: /login/token.php
      params:
        service: moodle_mobile_app

    principal:
      endpoint: /webservice/rest/server.php
      params:
        moodlewsrestformat: json
        wsfunction: core_webservice_get_site_info

    rest:
      endpoint: /webservice/rest/server.php
      params:
        moodlewsrestformat: json
      suppliers:
        wsfunction:
          location: param
          bean: es.ubu.lsi.ubumonitorweb.core.exception.ServiceFunctionParamSupplier

openapi:
  parameters:
    Moodle-Host:
      in: header
      description: URL base del servidor Moodle de destino.
  security-schemes:
    cookieAuth:
      type: apikey
      in: cookie
      name: auth-token
      description: Cookie con token JWE.
