spring:
  application:
    name: ubumonitorweb
  profiles:
    active: dev
  web:
    locale: en
  messages:
    fallback-to-system-locale: false

server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: strict


logging:
  level:
    org.springframework.security: debug
    es.ubu.lsi.ubumonitorweb: debug

security:
  public-routes:
    # Svelte App
    - /
    - /index.html
    - /favicon.png
    - /logo1.png
    - /_app/**

    - /actuator**
    - /swagger-ui/**
    - /swagger-ui/index.html
    - /v3/api-docs
  login-url: /api/login
  logout-url: /api/logout

service:
  default:
    host-header: Moodle-Host
    send-headers:
      - Accept-Language
    headers:
      Content-Type: application/x-www-form-urlencoded

  profiles:
    credentials:
      endpoint: /login/token.php
      params:
        service: moodle_mobile_app

    principal:
      endpoint: /webservice/rest/server.php
      params:
        moodlewsrestformat: json
        wsfunction: core_webservice_get_site_info

    webservice:
      endpoint: /webservice/rest/server.php
      params:
        moodlewsrestformat: json
      suppliers:
        wsfunction:
          location: param
          bean: es.ubu.lsi.ubumonitorweb.core.exception.ServiceFunctionParamSupplier

openapi:
  parameters:
    Moodle-Host:
      in: header
      description: URL base del servidor Moodle de destino.
