spring:
  application:
    name: ubumonitorweb
  web:
    locale: en
  messages:
    fallback-to-system-locale: false
  profiles:
    default: dev
  mvc:
    problemdetails:
      enabled: true

# Configuración de la cookie de sesión.
server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: strict

security:
  cookies-directory: ${user.home}/.umw/

logs:
  boolean-prefixes: [ is, has ]

clients:
  service-error-mappings:
    invalidlogin: unauthorized
    invalidtoken: forbidden
    nopermissions: forbidden
    apprequired: forbidden
    codingerror: bad_request
    invalid_parameter: bad_request
    sitepolicynotagreed: unavailable_for_legal_reasons
    autologinkeygenerationlockout: too_many_requests

  scraping-error-mappings:
    not-found:
      status: forbidden
      detail-selector: .errormessage

  profiles:
    default-get:
      host: es.ubu.lsi.ubumonitorweb.core.provider.HostProvider
      method: GET

    default-post:
      host: es.ubu.lsi.ubumonitorweb.core.provider.HostProvider
      method: POST

    # Perfil del cliente de obtención del token
    login-token-client:
      inherit: default-post
      endpoint: /login/token.php
      headers:
        Content-Type: application/x-www-form-urlencoded
      params:
        service: moodle_mobile_app

    # Perfil del cliente del formulario de login
    login-index-get-client:
      inherit: default-get
      endpoint: /login/index.php

    login-index-post-client:
      inherit: default-post
      endpoint: /login/index.php
      headers:
        Content-Type: application/x-www-form-urlencoded

    # Perfil del cliente del formulario de edición del perfil
    user-edit-client:
      inherit: default-get
      endpoint: /user/edit.php
      params:
        lang: en

    webservice-client:
      inherit: default-post
      endpoint: /webservice/rest/server.php
      headers:
        Content-Type: application/x-www-form-urlencoded
      params:
        moodlewsrestformat: json
      providers:
        wstoken:
          location: param
          bean: es.ubu.lsi.ubumonitorweb.core.provider.TokenProvider
        wsfunction:
          location: param
          bean: es.ubu.lsi.ubumonitorweb.core.provider.FunctionProvider

    autologin-client:
      inherit: webservice-client
      headers:
        User-Agent: MoodleMobile

    ajax-client:
      inherit: default-post
      endpoint: /lib/ajax/service.php
      multiple: true
      headers:
        Content-Type: application/json
      params:
        index: 0
      providers:
        args:
          location: param
          bean: es.ubu.lsi.ubumonitorweb.core.provider.ArgsProvider
        methodname:
          location: param
          bean: es.ubu.lsi.ubumonitorweb.core.provider.FunctionProvider

    # Perfil del cliente de recursos que requerirían cookies de sesión (usando token)
    resource-client:
      inherit: default-get
      endpoint: /webservice/pluginfile.php
      providers:
        token:
          location: param
          bean: es.ubu.lsi.ubumonitorweb.core.provider.TokenProvider

    # Perfil del cliente de reportes de logs
    log-client:
      inherit: default-get
      endpoint: /report/log/index.php
      params:
        logreader: logstore_standard
        download: csv
        chooselog: 1
        # Los nombres de los campos son siempre en inglés (para garantizar un mapeado correcto)
        lang: en
