security:
  public-routes:
    - /
    - /api/auth/discover
    - /api/auth/login-sso
    - /api/auth/login
    - /index.html
    - /*.js
    - /*.css
    - /*.ico
    - /*.svg
    - /*.gif
    - /*.png
    - /*.jpg
    - /*.jpeg
    - /*.webmanifest

# Jackson no lanza excepción y convierte los valores null
# en ceros para los tipos numéricos primitivos
spring:
  jackson:
    deserialization:
      fail-on-null-for-primitives: false

# Actuator
management:
  endpoints:
    access:
      default: none

# Springdoc
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
