security:
  public-routes:
    - /
    - /api/auth/discover
    - /api/auth/login-sso
    - /api/auth/login
    - /index.html
    - /*.js
    - /*.css
    - /*.ico
    - /*.svg
    - /*.gif
    - /*.png
    - /*.jpg
    - /*.jpeg
    - /*.webmanifest

    # Actuator
    - /actuator**

    # Springdoc
    - /v3/api-docs
    - /swagger-ui/**

logging:
  level:
    es.ubu.lsi.ubumonitorweb: trace
    org.apache.hc.client5.http.headers: DEBUG
