spring:
  application:
    name: ubumonitorweb
  web:
    locale: en
  messages:
    fallback-to-system-locale: false
  profiles:
    default: dev
  mvc:
    problemdetails:
      enabled: true

# Configuración de la cookie de sesión.
server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: strict

client:
  profiles:
    # Perfil con propiedades globales para peticiones GET
    default-get:
      host: es.ubu.lsi.ubumonitorweb.core.client.ClientHostProvider
      forward-headers:
        - Accept-Language

    # Perfil con propiedades globales para peticiones GET
    default-post:
      inherit: default-get
      headers:
        Content-Type: application/x-www-form-urlencoded

    # Perfil del cliente de obtención del token
    token-client:
      inherit: default-post
      endpoint: /login/token.php
      params:
        service: moodle_mobile_app

    # Perfil del cliente del formulario de login
    login-client:
      inherit: default-get
      endpoint: /login/index.php

    # Perfil del cliente del formulario de edición del perfil
    user-edit-client:
      inherit: default-get
      endpoint: /user/edit.php

    # Perfil del cliente de recursos que requerirían cookies de sesión (usando token)
    resource-client:
      inherit: default-get
      endpoint: /webservice/pluginfile.php
      providers:
        token:
          location: param
          bean: es.ubu.lsi.ubumonitorweb.core.client.ClientTokenProvider

    # Perfil del cliente de reportes de logs
    log-client:
      inherit: default-get
      endpoint: /report/log/index.php
      params:
        logreader: logstore_standard
        download: csv
        chooselog: 1
        # Los nombres de los campos son siempre en inglés (para garantizar un mapeado correcto)
        lang: en
      providers:
        MoodleSession:
          location: cookie
          bean:  es.ubu.lsi.ubumonitorweb.core.client.ClientCookieProvider

    # Perfil de los clientes del webservice REST
    webservice-client:
      inherit: default-post
      endpoint: /webservice/rest/server.php
      params:
        moodlewsrestformat: json
      providers:
        wstoken:
          location: param
          bean: es.ubu.lsi.ubumonitorweb.core.client.ClientTokenProvider
        wsfunction:
          location: param
          bean: es.ubu.lsi.ubumonitorweb.core.client.ClientFunctionProvider
