package es.ubu.lsi.ubumonitorweb.feature.user.api

data class User(
  val id: Int,
  val fullname: String,
  val username: String?,
  val firstname: String?,
  val lastname: String?,
  val initials: String?,
  val email: String?,
  val address: String?,
  val phone1: String?,
  val phone2: String?,
  val department: String?,
  val institution: String?,
  val idnumber: String?,
  val interests: String?,
  val firstaccess: Long?,
  val lastaccess: Int?,
  val lastcourseaccess: Int?,
  val description: String?,
  val descriptionformat: Int?,
  val city: String?,
  val country: String?,
  val profileimageurl: String?,
  val customfields: Map<String, String>,
  val groups: List<String>,
  val roles: List<String>,
  val preferences: Map<String, String>,
  val enrolledcourses: List<String>,
)
