package es.ubu.lsi.ubumonitorweb.feature.course.dto

data class MoodleModule(
  val id: Int,
  val url: String? = null,
  val name: String,
  val instance: Int,
  val contextid: Int,
  val description: String? = null,
  val visible: Int,
  val uservisible: Boolean,
  val visibleoncoursepage: Int,
  val modicon: String,
  val modname: String,
  val purpose: String,
  val branded: Boolean,
  val modplural: String,
  val availability: String? = null,
  val indent: Int,
  val onclick: String,
  val afterlink: String? = null,
  val activitybadge: List<Any>? = null,
  val customdata: String,
  val noviewlink: Boolean,
  val candisplay: Boolean,
  val completion: Int,
  val completiondata: MoodleCompletionData? = null,
  val downloadcontent: Int,
  val dates: List<MoodleDate>,
  val groupmode: Int,
  val contents: List<MoodleContent>? = null,
  val contentsinfo: MoodleContentsInfo? = null,
)
